"""Drop unique key on conversion.exposure_id

Revision ID: 34de57eebce1
Revises: f03ae8a43826
Create Date: 2020-02-22 23:28:07.781292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34de57eebce1'
down_revision = 'f03ae8a43826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversion_exposure_id_key', 'conversion', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('conversion_exposure_id_key', 'conversion', ['exposure_id'])
    # ### end Alembic commands ###
