"""Add persistent sessions

Revision ID: 37618de9724e
Revises: 1216a8f364fa
Create Date: 2020-03-17 20:24:30.548581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37618de9724e'
down_revision = '1216a8f364fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_created_at'), 'session', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_updated_at'), 'session', ['updated_at'], unique=False)
    op.drop_index('ix_account_stripe_customer_id', table_name='account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_account_stripe_customer_id', 'account', ['stripe_customer_id'], unique=False)
    op.drop_index(op.f('ix_session_updated_at'), table_name='session')
    op.drop_index(op.f('ix_session_created_at'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
