"""add plans

Revision ID: 50a9a16519b9
Revises: 3978b8bc3a4b
Create Date: 2020-02-18 17:17:14.152228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4
from dataclasses import asdict

from app.models import Plan
from app.seeds import plans

# revision identifiers, used by Alembic.
revision = '50a9a16519b9'
down_revision = '3978b8bc3a4b'
branch_labels = None
depends_on = None


valid_keys = ['id', 'name', 'price_in_cents', 'max_subjects_per_experiment']
plan_dicts = [asdict(p) for p in plans]
valid_plan_dicts = [{k: plan_dict[k] for k in valid_keys} for plan_dict in plan_dicts]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_in_cents', sa.Integer(), nullable=False),
    sa.Column('max_subjects_per_experiment', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_name'), 'plan', ['name'], unique=False)
    op.add_column('account', sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('account_plan_id_fkey', 'account', 'plan', ['plan_id'], ['id'])
    op.bulk_insert(Plan.__table__, valid_plan_dicts)
    op.execute('update account set plan_id = (select id from plan where plan.price_in_cents=0 limit 1)')
    op.execute('alter table account alter column plan_id set not null')
    op.add_column('experiment', sa.Column('subjects_counter', sa.Integer()))
    op.execute('update experiment set subjects_counter=0 where subjects_counter is null')
    op.execute('alter table experiment alter column subjects_counter set not null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_plan_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'plan_id')
    op.drop_column('experiment', 'subjects_counter')
    op.drop_index(op.f('ix_plan_name'), table_name='plan')
    op.drop_table('plan')
    # op.drop_column('experiment', 'subjects_counter')
    # ### end Alembic commands ###
