"""add plan change tracking

Revision ID: 6e332fd22e34
Revises: 99ab26e65607
Create Date: 2020-03-08 17:44:41.733564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e332fd22e34'
down_revision = '99ab26e65607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_change',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('account_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_change_from_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_change_to_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['plan_change_from_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['plan_change_to_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_change_created_at'), 'plan_change', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_change_updated_at'), 'plan_change', ['updated_at'], unique=False)
    op.alter_column('order', 'account_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('order', 'plan_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_index(op.f('ix_order_amount'), 'order', ['amount'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_amount'), table_name='order')
    op.alter_column('order', 'plan_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('order', 'account_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_plan_change_updated_at'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_change_created_at'), table_name='plan_change')
    op.drop_table('plan_change')
    # ### end Alembic commands ###
