"""Add schedule to  plans

Revision ID: 8916265b8931
Revises: 63839d762be5
Create Date: 2020-03-06 23:41:27.979435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8916265b8931'
down_revision = '63839d762be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_schedule',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval', postgresql.INTERVAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_schedule_created_at'), 'plan_schedule', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_schedule_interval'), 'plan_schedule', ['interval'], unique=True)
    op.create_index(op.f('ix_plan_schedule_name'), 'plan_schedule', ['name'], unique=True)
    op.create_index(op.f('ix_plan_schedule_updated_at'), 'plan_schedule', ['updated_at'], unique=False)
    op.add_column('plan', sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('plan_plan_schedule_id_fkey', 'plan', 'plan_schedule', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plan_plan_schedule_id_fkey', 'plan', type_='foreignkey')
    op.drop_column('plan', 'schedule_id')
    op.drop_index(op.f('ix_plan_schedule_updated_at'), table_name='plan_schedule')
    op.drop_index(op.f('ix_plan_schedule_name'), table_name='plan_schedule')
    op.drop_index(op.f('ix_plan_schedule_interval'), table_name='plan_schedule')
    op.drop_index(op.f('ix_plan_schedule_created_at'), table_name='plan_schedule')
    op.drop_table('plan_schedule')
    # ### end Alembic commands ###
