"""add public field to plans

Revision ID: 91e81219d4ae
Revises: 6e332fd22e34
Create Date: 2020-03-08 19:29:41.440946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e81219d4ae'
down_revision = '6e332fd22e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('plan', sa.Column('self_serve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'public')
    op.drop_column('plan', 'self_serve')
    # ### end Alembic commands ###
