"""add downgrade fields to accounts

Revision ID: a7478a966ea0
Revises: 8916265b8931
Create Date: 2020-03-08 02:58:57.058552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7478a966ea0'
down_revision = '8916265b8931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('downgrade_at', sa.Date(), nullable=True))
    op.add_column('account', sa.Column('bill_at', sa.Date(), nullable=True))
    op.add_column('account', sa.Column('downgrade_plan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('account_downgrade_plan_id_fkey', 'account', 'plan', ['downgrade_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_downgrade_plan_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'downgrade_plan_id')
    op.drop_column('account', 'downgrade_at')
    op.drop_column('account', 'bill_at')
    # ### end Alembic commands ###
