"""track-last-exposure-ids

Revision ID: d72f8a7404ec
Revises: 34de57eebce1
Create Date: 2020-02-23 19:22:26.022062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd72f8a7404ec'
down_revision = '34de57eebce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohort', sa.Column('last_conversion_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('cohort', sa.Column('last_conversion_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('cohort', sa.Column('last_exposure_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('cohort', sa.Column('last_exposure_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('cohort_last_exposure_id_staging_fkey', 'cohort', 'exposure', ['last_exposure_id_staging'], ['id'])
    op.create_foreign_key('cohort_last_exposure_id_production_fkey', 'cohort', 'exposure', ['last_exposure_id_production'], ['id'])
    op.create_foreign_key('cohort_last_conversion_id_staging_fkey', 'cohort', 'conversion', ['last_conversion_id_staging'], ['id'])
    op.create_foreign_key('last_conversion_id_production', 'cohort', 'conversion', ['last_conversion_id_production'], ['id'])

    op.add_column('conversion', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    op.add_column('experiment', sa.Column('last_conversion_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('experiment', sa.Column('last_conversion_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('experiment', sa.Column('last_exposure_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('experiment', sa.Column('last_exposure_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('experiment_last_exposure_id_production_fkey', 'experiment', 'exposure', ['last_exposure_id_production'], ['id'])
    op.create_foreign_key('experiment_last_conversion_id_production_fkey', 'experiment', 'conversion', ['last_conversion_id_production'], ['id'])
    op.create_foreign_key('experiment_last_exposure_id_staging_fkey', 'experiment', 'exposure', ['last_exposure_id_staging'], ['id'])
    op.create_foreign_key('experiment_last_conversion_id_staging_fkey', 'experiment', 'conversion', ['last_conversion_id_staging'], ['id'])

    op.add_column('exposure', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    op.add_column('subject', sa.Column('last_conversion_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subject', sa.Column('last_conversion_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subject', sa.Column('last_exposure_id_production', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subject', sa.Column('last_exposure_id_staging', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('subject_last_exposure_id_production_fkey', 'subject', 'exposure', ['last_exposure_id_production'], ['id'])
    op.create_foreign_key('subject_last_conversion_id_production_fkey', 'subject', 'conversion', ['last_conversion_id_production'], ['id'])
    op.create_foreign_key('subject_last_exposure_id_staging_fkey', 'subject', 'exposure', ['last_exposure_id_staging'], ['id'])
    op.create_foreign_key('subject_last_conversion_id_staging_fkey', 'subject', 'conversion', ['last_conversion_id_staging'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_last_exposure_id_production_fkey', 'subject', type_='foreignkey')
    op.drop_constraint('subject_last_conversion_id_production_fkey', 'subject', type_='foreignkey')
    op.drop_constraint('subject_last_exposure_id_staging_fkey', 'subject', type_='foreignkey')
    op.drop_constraint('subject_last_conversion_id_staging_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'last_exposure_id_staging')
    op.drop_column('subject', 'last_exposure_id_production')
    op.drop_column('subject', 'last_conversion_id_staging')
    op.drop_column('subject', 'last_conversion_id_production')

    op.drop_column('exposure', 'last_seen_at')

    op.drop_constraint('experiment_last_exposure_id_production_fkey', 'experiment', type_='foreignkey')
    op.drop_constraint('experiment_last_conversion_id_production_fkey', 'experiment', type_='foreignkey')
    op.drop_constraint('experiment_last_exposure_id_staging_fkey', 'experiment', type_='foreignkey')
    op.drop_constraint('experiment_last_conversion_id_staging_fkey', 'experiment', type_='foreignkey')
    op.drop_column('experiment', 'last_exposure_id_staging')
    op.drop_column('experiment', 'last_exposure_id_production')
    op.drop_column('experiment', 'last_conversion_id_staging')
    op.drop_column('experiment', 'last_conversion_id_production')

    op.drop_column('conversion', 'last_seen_at')

    op.drop_constraint('cohort_last_exposure_id_production_fkey', 'cohort', type_='foreignkey')
    op.drop_constraint('cohort_last_conversion_id_production_fkey', 'cohort', type_='foreignkey')
    op.drop_constraint('cohort_last_exposure_id_staging_fkey', 'cohort', type_='foreignkey')
    op.drop_constraint('cohort_last_conversion_id_staging_fkey', 'cohort', type_='foreignkey')
    op.drop_column('cohort', 'last_exposure_id_staging')
    op.drop_column('cohort', 'last_exposure_id_production')
    op.drop_column('cohort', 'last_conversion_id_staging')
    op.drop_column('cohort', 'last_conversion_id_production')
    # ### end Alembic commands ###
