"""Addm ore indexes on referencing foreign keys

Revision ID: e71dea0cd6c3
Revises: e5297926559d
Create Date: 2020-03-26 14:16:33.912828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71dea0cd6c3'
down_revision = 'e5297926559d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_downgrade_plan_id'), 'account', ['downgrade_plan_id'], unique=False)
    op.create_index(op.f('ix_account_plan_id'), 'account', ['plan_id'], unique=False)
    op.create_index(op.f('ix_cohort_experiment_id'), 'cohort', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_cohort_last_conversion_id_production'), 'cohort', ['last_conversion_id_production'], unique=False)
    op.create_index(op.f('ix_cohort_last_conversion_id_staging'), 'cohort', ['last_conversion_id_staging'], unique=False)
    op.create_index(op.f('ix_cohort_last_exposure_id_production'), 'cohort', ['last_exposure_id_production'], unique=False)
    op.create_index(op.f('ix_cohort_last_exposure_id_staging'), 'cohort', ['last_exposure_id_staging'], unique=False)
    op.create_index(op.f('ix_contact_user_id'), 'contact', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversion_exposure_id'), 'conversion', ['exposure_id'], unique=False)
    op.create_index(op.f('ix_conversion_scope_id'), 'conversion', ['scope_id'], unique=False)
    op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)
    op.create_index(op.f('ix_experiment_last_conversion_id_production'), 'experiment', ['last_conversion_id_production'], unique=False)
    op.create_index(op.f('ix_experiment_last_conversion_id_staging'), 'experiment', ['last_conversion_id_staging'], unique=False)
    op.create_index(op.f('ix_experiment_last_exposure_id_production'), 'experiment', ['last_exposure_id_production'], unique=False)
    op.create_index(op.f('ix_experiment_last_exposure_id_staging'), 'experiment', ['last_exposure_id_staging'], unique=False)
    op.create_index(op.f('ix_experiment_user_id'), 'experiment', ['user_id'], unique=False)
    op.create_index(op.f('ix_exposure_cohort_id'), 'exposure', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_exposure_experiment_id'), 'exposure', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_exposure_scope_id'), 'exposure', ['scope_id'], unique=False)
    op.create_index(op.f('ix_exposure_subject_id'), 'exposure', ['subject_id'], unique=False)
    op.create_index(op.f('ix_order_account_id'), 'order', ['account_id'], unique=False)
    op.create_index(op.f('ix_order_plan_id'), 'order', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payment_method_account_id'), 'payment_method', ['account_id'], unique=False)
    op.create_index(op.f('ix_plan_schedule_id'), 'plan', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_plan_change_account_id'), 'plan_change', ['account_id'], unique=False)
    op.create_index(op.f('ix_plan_change_order_id'), 'plan_change', ['order_id'], unique=False)
    op.create_index(op.f('ix_plan_change_plan_change_from_id'), 'plan_change', ['plan_change_from_id'], unique=False)
    op.create_index(op.f('ix_plan_change_plan_change_to_id'), 'plan_change', ['plan_change_to_id'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_index(op.f('ix_subject_account_id'), 'subject', ['account_id'], unique=False)
    op.create_index(op.f('ix_subject_last_conversion_id_production'), 'subject', ['last_conversion_id_production'], unique=False)
    op.create_index(op.f('ix_subject_last_conversion_id_staging'), 'subject', ['last_conversion_id_staging'], unique=False)
    op.create_index(op.f('ix_subject_last_exposure_id_production'), 'subject', ['last_exposure_id_production'], unique=False)
    op.create_index(op.f('ix_subject_last_exposure_id_staging'), 'subject', ['last_exposure_id_staging'], unique=False)
    op.create_index(op.f('ix_subject_scope_id'), 'subject', ['scope_id'], unique=False)
    op.create_index(op.f('ix_token_account_id'), 'token', ['account_id'], unique=False)
    op.create_index(op.f('ix_token_role_id'), 'token', ['role_id'], unique=False)
    op.create_index(op.f('ix_token_scope_id'), 'token', ['scope_id'], unique=False)
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_account_id'), 'user', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_id'), table_name='user')
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_index(op.f('ix_token_scope_id'), table_name='token')
    op.drop_index(op.f('ix_token_role_id'), table_name='token')
    op.drop_index(op.f('ix_token_account_id'), table_name='token')
    op.drop_index(op.f('ix_subject_scope_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_last_exposure_id_staging'), table_name='subject')
    op.drop_index(op.f('ix_subject_last_exposure_id_production'), table_name='subject')
    op.drop_index(op.f('ix_subject_last_conversion_id_staging'), table_name='subject')
    op.drop_index(op.f('ix_subject_last_conversion_id_production'), table_name='subject')
    op.drop_index(op.f('ix_subject_account_id'), table_name='subject')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_plan_change_plan_change_to_id'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_change_plan_change_from_id'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_change_order_id'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_change_account_id'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_schedule_id'), table_name='plan')
    op.drop_index(op.f('ix_payment_method_account_id'), table_name='payment_method')
    op.drop_index(op.f('ix_order_plan_id'), table_name='order')
    op.drop_index(op.f('ix_order_account_id'), table_name='order')
    op.drop_index(op.f('ix_exposure_subject_id'), table_name='exposure')
    op.drop_index(op.f('ix_exposure_scope_id'), table_name='exposure')
    op.drop_index(op.f('ix_exposure_experiment_id'), table_name='exposure')
    op.drop_index(op.f('ix_exposure_cohort_id'), table_name='exposure')
    op.drop_index(op.f('ix_experiment_user_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_last_exposure_id_staging'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_last_exposure_id_production'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_last_conversion_id_staging'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_last_conversion_id_production'), table_name='experiment')
    op.drop_index(op.f('ix_event_user_id'), table_name='event')
    op.drop_index(op.f('ix_conversion_scope_id'), table_name='conversion')
    op.drop_index(op.f('ix_conversion_exposure_id'), table_name='conversion')
    op.drop_index(op.f('ix_contact_user_id'), table_name='contact')
    op.drop_index(op.f('ix_cohort_last_exposure_id_staging'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_last_exposure_id_production'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_last_conversion_id_staging'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_last_conversion_id_production'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_experiment_id'), table_name='cohort')
    op.drop_index(op.f('ix_account_plan_id'), table_name='account')
    op.drop_index(op.f('ix_account_downgrade_plan_id'), table_name='account')
    # ### end Alembic commands ###
