"""Add Account.stripe_customer_id

Revision ID: fa3692965b28
Revises: 5a68f489ae9e
Create Date: 2020-03-09 18:04:36.100191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3692965b28'
down_revision = '5a68f489ae9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('account', sa.Column('stripe_livemode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'stripe_customer_id')
    op.drop_column('account', 'stripe_livemode')
    # ### end Alembic commands ###
