name: CI
on: [push]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker containers
        run: docker-compose build
      - name: Start docker containers
        run: docker-compose up --detach
      - name: Log container status
        run: docker-compose ps
      - name: Run seeds
        run: docker-compose exec -T web flask db upgrade
      - name: Run tests
        run: docker-compose exec -T web pytest tests/
