name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: quicksplit
          POSTGRES_PASSWORD: notsecret
          POSTGRES_DB: quicksplit-dev
        ports:
          - '5432:5432'
      redis:
        image: redis
        ports:
          - '6379:6379'
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run migrations
        run: flask db upgrade
      - name: Seed database
        run: flask seed all
      - name: Start app
        run: heroku local > logs.txt &
      - name: Run tests
        run: pytest
      # - name: Deploy to Heroku staging
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP_NAME: quicksplit-testing
      #   run: heroku git:remote quicksplit-test && git push heroku heroku-review-apps:master
      # - name: Test web requests against Heroku release
      #   run: docker-compose run --rm -e QUICKSPLIT_API_URL=https://api.quicksplit.io web pytest tests/test_api.py
      #   if: github.ref == 'refs/heads/master'
      # - name: Test locally installed CLI against Heroku release
      #   run: docker-compose run --rm -e QUICKSPLIT_API_URL=https://api.quicksplit.io web pytest tests/test_cli.py
      #   if: github.ref == 'refs/heads/master'
      # - name: Test PyPI deployed CLI against Heroku releases
      #   if: github.ref == 'refs/heads/master'
      #   env:
      #     QUICKSPLIT_API_URL: https://api.quicksplit.io
      #   run: |
      #     pip --version
      #     pip install quicksplit pytest
      #     pip list
      #     pytest ./tests/test_cli.py --noconftest
