name: PyPI Deployment
on:
  release:
    types:
      - created
jobs:
  deploy-pypi:
    name: Deploy CLI to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set TAG
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Print TAG
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy-cli
        with:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: tjwaterman99
      - name: Test PyPI deployed CLI against Heroku releases
        env:
          QUICKSPLIT_API_URL: https://api.quicksplit.io
        run: |
          sleep 60  # Wait for PyPI to publish release
          pip --version
          pip install quicksplit==$RELEASE_VERSION pytest
          pip list
          pytest ./tests/test_cli.py --noconftest
