name: PyPI Deployment
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  deploy-pypi:
    name: Deploy CLI to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set TAG
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Print TAG
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy-cli
        with:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: tjwaterman99
